#!/usr/bin/env php
<?php

set_time_limit(0);
define("ROOTDIR", __DIR__);

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new Twpf\Console\TelegramCommandCreationCommand());

$application->run();